// para autocompletar
/// <reference types="cypress" />

describe('Llena los campos y crea una cita', () => {
    it('Campos nueva cita', () => {
        cy.visit('/Agenda-una-cita/')
        cy.get('[data-cy=mascota-input]')
            .type('Kira')
        cy.get('[data-cy=propietario-input]')
            .type('Alejandro')
        cy.get('[data-cy=telefono-input]')
            .type('2235815306')
        cy.get('[data-cy=fecha-input]')
            .type('2021-01-12')
        cy.get('[data-cy=hora-input]')
            .type('16:16')
        cy.get('[data-cy=sintomas-textarea]')
            .type('Juega mucho')
        cy.get('[data-cy=submit-cita]')
            .click()
        cy.get('[data-cy="citas-heading"]')
            .invoke('text')
            .should('equal', 'Administra tus Citas')
        cy.get('[data-cy=alerta]')
            .invoke('text')
            .should('equal', 'Se agregó correctamente')
        cy.get('[data-cy=alerta]')
            .should('have.class', 'alert-success')
    })
})